### Welcome to Jekyll Config File
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

### Webpage configuration
title: NotKaskus
short_logo: NotKaskus (Paul)
description: >
  Hobby JavaScript-Developer creating API, Bots and NodeJS Projects.
baseurl: ""
url: https://paul.is-a.dev

### Author configuration
author:
  name: NotKaskus
  github: NotKaskus
  email: kaskus45@proton.me
  homepage: https://paul.is-a.dev
  twitter: TrueKaskus
  discord: https://discord.gg/XcbMwAyUJ9
  instagram: https://www.instagram.com/its_paul2006/
  anilist: https://anilist.co/user/KASKUS/
twitter:
  username: TrueKaskus
logo: favicon.png

# Google Analytics and Disqus comments, this setting will turn on Google Analytics and Disqus comments.
disqus_name: notkaskus
g_track_id: G-MHF08CJFCZ

### Build settings
markdown: kramdown
timezone: Asia/Manila
plugins:
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  -
    scope:
      path: _posts
    values:
      comments: true
  -
    scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false
  -
    scope:
      path: pages/tags
    values:
      layout: tag
      sitemap:
        priority: 0.4

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: []
  
feed:
  tags: true

rss: true
dark_mode: true
project_card_style: modal

### Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
